baseURL = "https://smartbackpacker.github.io/website/"
languageCode = "en-us"
title = "Smart Backpacker App"
theme = "beautiful"
publishDir = "docs"
relativeURLs = true

[Params]
  subtitle = "Easily find Visa Requirements, Currency Exchange and Airline's Baggage Policy!"
  logo = "img/sb.png"
  favicon = "img/sb.ico"
  commit = false

[Author]
  name = "Gabriel Volpe"
  website = "www.smartbackpackerapp.com"
  email = "smartbackpackerapp@gmail.com"
  facebook = "smartbackpackerapp"
  github = "SmartBackpacker"
  twitter = "SmBackpackerApp"
  instagram = "smartbackpackerapp"

[[menu.main]]
    name = "Blog"
    url = "http://blog.smartbackpackerapp.com"
    weight = 1
